import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Provider from "./context/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function () {
        try {
          const theme = localStorage.getItem("theme") || "dark";
          document.documentElement.classList.add(theme);
        } catch (e) {}
        })();`,
          }}
        />
      </head>
      <body className={`${inter.variable} antialiased overflow-x-hidden`}>
        <Provider>
          {" "}
          {children} <Footer />{" "}
        </Provider>
      </body>
    </html>
  );
}
